version: '3.0.3.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

install:
  - call C:\\Miniconda36-x64\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -n csm
  - conda install -c conda-forge cmake
  - conda activate csm

before_build:
  - mkdir build
  - cd build

build_script:
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --target ALL_BUILD --config Release

artifacts:
  - path: build\Release\csmapi.dll
    name: csmapi.dll
  - path: build\Release\csmapi.lib
    name: csmapi.lib
